// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZxcGaMriSmv2A8gnWL5h4LVRZ_Jp5c98',
    appId: '1:1079869642904:web:7825ab0f3deb455cf618ed',
    messagingSenderId: '1079869642904',
    projectId: 'sjd-store-app',
    authDomain: 'sjd-store-app.firebaseapp.com',
    storageBucket: 'sjd-store-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA73siotC5rVYiLApP1a8J01pM9eMW5xsA',
    appId: '1:1079869642904:android:384fe515960786fff618ed',
    messagingSenderId: '1079869642904',
    projectId: 'sjd-store-app',
    storageBucket: 'sjd-store-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhvuxuQn7yy3DzOL8v5z3HDHSK4ru-2PI',
    appId: '1:1079869642904:ios:3f1179f34ed43c72f618ed',
    messagingSenderId: '1079869642904',
    projectId: 'sjd-store-app',
    storageBucket: 'sjd-store-app.appspot.com',
    iosClientId: '1079869642904-lquv3r60ledhe8g5pojh1vlhr7uo9p8v.apps.googleusercontent.com',
    iosBundleId: 'com.sjd-store.app',
  );
}
